spring:
  application:
    name: notification
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    queue:
      name: fraudsters-one
  zipkin:
    enabled: true
    baseUrl: http://zipkin:9411